- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "ansible-rg"
        location: "westeurope"
      register: rg
    - debug:
        var: rg

    - name: Create Virtual Network
      azure_rm_virtualnetwork:
        name: "ansible-vnet"
        resource_group: "ansible-rg"
        address_prefixes: "10.0.0.0/16"
      register: vnet
    - debug:
        var: vnet

    - name: Adding subnet in ansible-vnet
      azure_rm_subnet:
        name: "Subnet"
        virtual_network_name: "ansible-vnet"
        resource_group: "ansible-rg"
        address_prefix: "10.0.0.0/24"
      register: subnet
    - debug: 
        var: subnet

    - name: Create public ip address
      azure_rm_publicipaddress:
        name: "pubip"
        resource_group: "ansible-rg"
        allocation_method: "static"
      register: pub_ip_address
    
    - debug:
        msg: "The public ip is  {{ pub_ip_address.state.ip_address }}."
    
    - name: Create network security group that allows ssh
      azure_rm_securitygroup:
        name: "ansible-nsg"
        resource_group: "ansible-rg"
        rules:
          - name: "ssh"
            protocol:  "Tcp"
            destination_port_range: 22
            access: "Allow"
            priority: 1001
            direction: "Inbound"
      register: nsg
    - debug: 
        var: nsg

    - name: Create network interface card
      azure_rm_networkinterface:
        name: "ansible-nic"
        resource_group: "ansible-rg"
        virtual_network: "ansible-vnet"
        subnet: "Subnet"
        ip_configurations:
          - name: "ipconf"
            public_ip_address_name: "pubip"
            primary: true
        security_group: "ansible-nsg"

    - name: Create Linux Vm
      azure_rm_virtualmachine:
        name: "ansible-linux-vm"
        resource_group: "ansible-rg"
        vm_size: "Standard_B2ms"
        admin_username: "azureuser"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/home/azureuser/.ssh/authorized_keys"
            key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1hm7xGH5xuHls5/6ZTqsPJGPu5RgEGK8wRdVDj8iMdxlwmhzDPa/TNXveVSU/3mL4H5X34XRkt09/rD6eeuMCfnTzIfEZgshX71nC2ckbSCCdz123ElX1vnyfqWAnlGk/FaOgJht2EQF5OpLAgmsnZhnVBVy5j9pVsGJJ2/A+i3bMhFM5N/7NRrwR9sQW7dHqKC5mOIKefd3ZSWqpCa0Cq/ihLosWi+q6OXzqZXUuggc2fNSz1TahLLtwud3XH+SUVY8ciwVqqXKGAM+rx4olu9LKFYmzBTMttyX6sueYnNacFTb8E99EFETZOlUPCg5v73+3fgA3DJW8jnGujDEpH+5p1ZQHk9kEhze1+OOvcJSZwJGsqZdwI6qAc4Fr0Gghl4NaconmR7N1EWfVkluv4txskP7LbpvSFiSFjgVFDRaPXdbH+B3hYA/DLeQSOOicDP6FEXMkPrl+zP01g6EFlsnXRtuOTpV/6CZCfhv7//QmoNDWCmhqKklgJDCDbPWmTfgucPH06IHhPuBuHHQjqW7BhHeAGmtSBaimOu2cfrtbYDkXH87Emmmixkb+dFvwD8hkPfljQDNHjuG5vvwgqHVhSoKimHuwwUOz5OeEH/F4svIL7OD+O7MqBvuCue4qCTnTjlEk/5A53qJ+urnoXa8sOaC9N5lSD0suo17UcQ== prafull@DELLA0084"
        network_interfaces: "ansible-nic"
        managed_disk_type: "Standard_LRS"
        image:
          offer: "0001-com-ubuntu-server-focal"
          publisher: "canonical"
          sku: "20_04-lts-gen2"
          version: "latest"



